version: '2'

services:

  php-server:
    image: php:5-apache

    volumes:
      - "./public:/var/www/html"
      - "./src:/var/www/src"
      - "./config:/var/www/config"
      - "./resources:/var/www/resources"
      - "./vendor:/var/www/vendor"

    ports:
      - "8080:80"
    restart: always
