<?php
/**
 * Copyright 2019 (C) IDFyed Solutions AB
 *
 * Emulates a request from the Diglias app without having to actually scan a static QR code.
 *
 * Prepare a message to the Diglias GO service and redirect the users
 * browser to Diglias to ask the user to authenticate. This step is intended
 * for emulation of the App-Initated flow, this is not part of the normal
 * application flow.
 *
 * @author jonas
 *
 */

require '../../../vendor/autoload.php';
require '../../../config/config.php';

use Diglias\EAPI\RelyingParty;

use sample\Util;



$params = array(

    // Add application specific options (URL:s)
    'auth_returnlink' => Util::buildEndpointURL("/app-initiated/transform.php"),
    'auth_cancellink' => Util::buildEndpointURL("/authenticate/cancel.php"),
    'auth_rejectlink' => Util::buildEndpointURL("/authenticate/reject.php"),

    // Pass the QR code payload as RelayState for the purpose of emulation.
    'RelayState' => $_POST["payload"],

    // Generate a random request id, in the case of app initiated this value will
    // be generated by the Diglias Go service and included as input.
    'auth_requestid' => Util::generateRandomString()
);


// Build the URL and redirect the users browser to it.
$RP = new RelyingParty(COMPANY_NAME, MAC_KEY, EAPI_ENDPOINT);
header('Location: ' . $RP->buildAuthnURL($params), true, 302);
